export const API_URL = {
  url: import.meta.env.VITE_API_URL + "/api",
  baseUrl: import.meta.env.VITE_API_URL,
  users: "users",
  login: "auth/login",
  register: "register",
  movies: "movies",
  genremovie: "genre_movies",
  accounts: "accounts",
  rooms: "rooms",
  showtime: "showtime",
  room: "room",
  chairs: "chairs",
  showtimeSlots: "showtime-slots",
  showtimes: "showtimes",
  products: "products",
  promotions: "promotions",
  tickets: "tickets",
  bookings: "bookings",
  payments: "payments",
  comment: "comments",
  vnpay: "vnpay/payment",
  bookingsAccount: "bookings/account",
  momo: "momo-payment",
  redeem_discount: "redeem-discount",
  revenueByMovie: "revenue-by-movie",
};
